### ISSUE TITLE
release-version functionality does not work with uv

### ISSUE THREAD

**Issue by brandonthorly** [lucasvieirasilva/nx-plugins#266]
### Current Behavior

nx release fails for UV projects. 

// project.json
```
"release": {
    "version": {
      "generator": "@nxlv/python:release-version",
      "generatorOptions": {
        "updateDependents": "auto",
        "packageManager": "uv"
      }
    }
  },

```

// nx.json
```
"plugins": [
    {
      "plugin": "@nxlv/python",
      "options": {
        "packageManager": "uv"
      }
    }
  ],
"release": {
    "projects": [
      "*",
      "!*_workflow"
    ],
    "projectsRelationship": "independent",
    "version": {
      "conventionalCommits": true
    },
    "git": {
      "commitMessage": "chore: bump affected semvers"
    },
    "changelog": {
      "projectChangelogs": {
        "file": "{projectRoot}/CHANGELOG.md",
        "createRelease": "github",
        "renderOptions": {
          "authors": false,
          "commitReferences": true,
          "versionTitleDate": true
        }
      }
    },
    "releaseTagPattern": "v{version}-{projectName}"
  }

```

### Expected Behavior

npx nx release works in the same way as with poetry

### Steps to Reproduce

1. create an nx workspace with python project with the UV package manager
2. run npx nx release

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node           : 23.6.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.9.2

nx             : 20.3.1
@nx/js         : 20.3.1
@nx/workspace  : 20.3.1
@nx/devkit     : 20.3.1
typescript     : 5.6.3
---------------------------------------
Registered Plugins:
@nxlv/python
---------------------------------------
Community plugins:
@nxlv/python : 20.3.4
```

### Failure Logs

```shell
✗ npx nx release --first-release --skip-publish --dry-run --verbose
// my added console logs
options release-version,  { packageManager: 'uv' }
options resolver undefined
provider,  PoetryProvider {
  workspaceRoot: '.',
  logger: Logger {},
  tree: FsTree {
    root: 'REPO_DIR',
    isVerbose: true,
    logOperationId: undefined,
    recordedChanges: {},
    locked: false
  },
  isProjectDependent: [Function (anonymous)]
}

 NX   Dependency not found

Error: Dependency not found
    at PoetryProvider.getDependencyMetadata (/node_modules/@nxlv/python/src/provider/poetry/provider.js:95:15)
    at Package.getLocalDependency (/node_modules/@nxlv/python/src/generators/release-version/utils/package.js:15:43)
    at resolveLocalPackageDependencies (/node_modules/@nxlv/python/src/generators/release-version/utils/resolve-local-package-dependencies.js:45:58)
    at /node_modules/@nxlv/python/src/generators/release-version/release-version.js:351:123
    at Generator.next (<anonymous>)
    at fulfilled (/node_modules/tslib/tslib.js:167:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
```

### Additional Information

some spots i noticed glancing quickly through the code...

* the release-version code calls getProvider with [options](https://github.com/lucasvieirasilva/nx-plugins/blob/main/packages/nx-python/src/generators/release-version/release-version.ts#L48) to select the correct provider
* the [getProvider method](https://github.com/lucasvieirasilva/nx-plugins/blob/main/packages/nx-python/src/provider/resolver.ts#L21C3-L32C4) works as expected and returns UVProvider if set to 'uv' and PoetryProvider if set to 'poetry', currently it sets to 'uv' if any 'packageManager' is set.
* [UVProvider.getDependencyMetadata](https://github.com/lucasvieirasilva/nx-plugins/blob/main/packages/nx-python/src/provider/uv/provider.ts#L88-L113)

**Comment by lucasvieirasilva** [comment]
@brandonthorly thanks for raising this issue, apparently, the package manager is not being detected correctly.

are you using `uv` with workspace more?

**Comment by brandonthorly** [comment]
hi @lucasvieirasilva ,

i'm not using the uv workspace approach. each project has its own venv. 

when i overrode [this code](https://github.com/lucasvieirasilva/nx-plugins/blob/main/packages/nx-python/src/generators/release-version/release-version.ts#L48) locally to call `getProvider` with options and the UVProvider was returned i noticed that the `getDependencyMetadata` is looking for a root lockfile.

**Comment by lucasvieirasilva** [comment]
Thanks @brandonthorly, it's definitely a bug, I'm fixing it right now

**Comment by lucasvieirasilva** [comment]
Hi @brandonthorly, I just released a fix, version `20.3.5`.

you're gonna need to change your `nx.json` as follow:

```json
{
  ...
  "plugins": [
    ...
    {
      "plugin": "@nxlv/python",
      "options": {
        "packageManager": "uv"
      }
    }
  ]
  ...
}
```

**Comment by brandonthorly** [comment]
thanks for the fast response @lucasvieirasilva !

i already had the updated plugin in my nx.json file. just bumped to 20.3.5 and tried again. 

are uv.lock files required for the projects? i usually exclude these when building libraries (half of my new monorepo). i added them in to test this and am still getting the error below.

i'm getting the UVProvider now but looks like i'm still getting issues in UVProvider.getDependencyMetadata

```
 NX   Cannot read properties of undefined (reading 'name')

TypeError: Cannot read properties of undefined (reading 'name')
    at UVProvider.getDependencyMetadata (/node_modules/@nxlv/python/src/provider/uv/provider.js:68:52)
    at Package.getLocalDependency (/node_modules/@nxlv/python/src/generators/release-version/utils/package.js:15:43)
    at resolveLocalPackageDependencies (/node_modules/@nxlv/python/src/generators/release-version/utils/resolve-local-package-dependencies.js:45:58)
    at /node_modules/@nxlv/python/src/generators/release-version/release-version.js:350:123
    at Generator.next (<anonymous>)
    at fulfilled (/node_modules/tslib/tslib.js:167:62)
```

any ideas?

**Comment by lucasvieirasilva** [comment]
@brandonthorly I've used the lock file in this operation to keep the code consistent with the workspace version.

but I can add the support for projects without the uv.lock for this case.

**Comment by lucasvieirasilva** [comment]
The plugin resolves the package name from the `pyproject.toml`, so, the snake case should not be a problem

**Comment by lucasvieirasilva** [comment]
@brandonthorly I just release a new version that doesn't use the lock file in the release-version feature, please let me know if works or not.

**Comment by brandonthorly** [comment]
@lucasvieirasilva looking good! thanks again for the quick turnaround here. 💯
